### ISSUE TITLE
Switch generator property names to expressions

### ISSUE THREAD

**Issue by thelonious** [gentleman-programmer/gp-data-transformer#12]
Currently, we use identifiers for property names in object generators. I think we'll get more flexibility if we require property names to be expressions. This means that instead of:

```
{ a: true }
```

we'll need something more JSON-like:

```
{ "a": true }
```

This will allow us to "calculate" the property name. Say we use this data
```
{ "bezier2": "QuadraticBezier" }
```
and then apply this transform
```
{ v: k } <= { string as k: value as v }
    results in { "QuadraticBezier": "bezier2" }
```
Note that this implies that object pattern might need to be expanded to allow captures of property names in general. The example above doesn't feel quite right since keys are always strings (or is that true only for JSON?)

**Comment by thelonious** [comment]
This makes me think that we may need property groups, like we have element groups:

```
_ <= { (*: value); 5 as pair}
```

This says that we expect an object with five properties. The result will be an array of objects. Each object will have a single property and value. However, if we capture the keys and values separately, like so:

```
[ ks, vs ] <= { (* as ks: value as vs); 5}
```

This will result in two arrays, ks and vs. ks will hold all matched keys and vs will hold all matched values

**Comment by thelonious** [comment]
As an aside, enumerations could be a useful way to limit what property names are allowed in a property pattern.

```
type Names = [ "one", "two", "three" ]
[ ks, vs ] <= { (Names as ks: value as vs); 3 }
```

This says that the property has to be "one", "two", or "three" only

**Comment by gentleman-programmer** [comment]
The overall syntax of dt has changed a fair amount. None of the above examples are valid. However, here's an example of how this can be used:

```
let a = "name"; { a: "Test" }
```

This is contrived, but this shows 'a' in the object is an identifier. It's value will be looked up in the current scope. As a result 'a' becomes 'name' give us:

```
{ "name": "Test" }
```
